import React, {ReactElement} from 'react';
import {Helmet} from 'react-helmet';


export interface IAppCommonHeadProps {
    readonly basePath?: string;
}

export function AppHelmet({basePath}: IAppCommonHeadProps): ReactElement {
    const prefix = basePath || '';

    const robotoPath = `${prefix}/fonts/roboto/roboto-v20-latin-regular.woff`;
    const roboto2Path = `${prefix}/fonts/roboto/roboto-v20-latin-regular.woff2`;

    const robotoCondensedPath = `${prefix}/fonts/roboto-condensed/roboto-condensed-v18-latin-regular.woff`;
    const robotoCondensed2Path = `${prefix}/fonts/roboto-condensed/roboto-condensed-v18-latin-regular.woff2`;

    const fontAttributes = {as: "font", type: "font/woff2", crossOrigin: "anonymous"};

    return (
        <Helmet>

            {/*
                preload fonts
            */}
            <link rel="preload" href={roboto2Path} {...fontAttributes}/>
            <link rel="preload" href={robotoCondensed2Path} {...fontAttributes}/>
            <style type="text/css">{`
                @font-face {
                    font-family: "Roboto";
                    font-style: normal;
                    font-weight: 400;
                    font-display: swap;
                    src: local("Roboto"), local("Roboto-Regular"),
                         url("${roboto2Path}") format("woff2"),
                         url("${robotoPath}") format("woff");
                }

                @font-face {
                    font-family: "Roboto Condensed";
                    font-style: normal;
                    font-weight: 400;
                    font-display: swap;
                    src: local("Roboto Condensed"), local("RobotoCondensed-Regular"),
                         url("${robotoCondensed2Path}") format("woff2"),
                         url("${robotoCondensedPath}") format("woff");
                }
            `}</style>

            {/*
                icons - based on code generated by https://realfavicongenerator.net
                (see app-common README.md)
            */}
            <link rel="apple-touch-icon" sizes="180x180" href={`${prefix}/apple-touch-icon.png`}/>
            <link rel="icon" type="image/png" sizes="32x32" href={`${prefix}/favicon-32x32.png`}/>
            <link rel="icon" type="image/png" sizes="16x16" href={`${prefix}/favicon-16x16.png`}/>
            <link rel="manifest" href={`${prefix}/site.webmanifest`}/>
            <link rel="mask-icon" href={`${prefix}/safari-pinned-tab.svg`} color="#5050ff"/>
            <link rel="shortcut icon" href={`${prefix}/favicon.ico`}/>
            <meta name="apple-mobile-web-app-title" content="AGE Online"/>
            <meta name="application-name" content="AGE Online"/>
            <meta name="msapplication-TileColor" content="#da532c"/>
            <meta name="msapplication-config" content={`${prefix}/browserconfig.xml`}/>
            <meta name="theme-color" content="#5050ff"/>

        </Helmet>
    );
}
