module.exports = {

    extends: [
        'eslint:recommended',
    ],

    rules: {
        'array-bracket-newline': [2, 'consistent'],
        'arrow-body-style': 2,
        'arrow-spacing': 2,
        'block-spacing': 2,
        'brace-style': 2,
        camelcase: 2,
        'comma-dangle': [2, 'always-multiline'],
        'comma-spacing': 2,
        'comma-style': 2,
        'computed-property-spacing': 2,
        curly: 2,
        'default-param-last': 2,
        'dot-location': [2, 'property'],
        'dot-notation': 2,
        'eol-last': 2,
        eqeqeq: 2,
        'func-call-spacing': 2,
        'func-style': [2, 'declaration', {allowArrowFunctions: true}],
        'function-paren-newline': [2, 'consistent'],
        'generator-star-spacing': 2,
        'implicit-arrow-linebreak': 2,
        indent: [2, 4, {
            SwitchCase: 1,
            FunctionDeclaration: {parameters: 'first'},
            FunctionExpression: {parameters: 'first'},
            VariableDeclarator: 'first',
            // ignore JSX nodes:
            // https://github.com/typescript-eslint/typescript-eslint/issues/415#issuecomment-507385565
            ignoredNodes: ['JSXAttribute', 'JSXSpreadAttribute'],
        }],
        'keyword-spacing': 2,
        'key-spacing': 2,
        'linebreak-style': 2,
        'max-len': [2, {code: 120, ignoreUrls: true}],
        'multiline-ternary': [2, 'always-multiline'],
        'new-cap': 2,
        'new-parens': 2,
        'newline-per-chained-call': 2,
        'no-alert': 2,
        'no-array-constructor': 2,
        'no-await-in-loop': 2,
        'no-bitwise': 2,
        'no-caller': 2,
        'no-confusing-arrow': 2,
        'no-console': 2,
        'no-dupe-class-members': 2,
        'no-else-return': 2,
        'no-empty-function': 2,
        'no-eval': 2,
        'no-extend-native': 2,
        'no-floating-decimal': 2,
        'no-implied-eval': 2,
        'no-invalid-this': 2,
        'no-iterator': 2,
        'no-labels': 2,
        'no-lone-blocks': 2,
        'no-lonely-if': 2,
        'no-loop-func': 2,
        'no-loss-of-precision': 2,
        'no-mixed-operators': 2,
        'no-multi-spaces': 2,
        'no-multi-str': 2,
        'no-multiple-empty-lines': [2, {max: 3}],
        'no-negated-condition': 2,
        'no-new': 2,
        'no-new-func': 2,
        'no-new-object': 2,
        'no-new-wrappers': 2,
        'no-octal-escape': 2,
        'no-param-reassign': 2,
        'no-proto': 2,
        'no-return-assign': 2,
        'no-return-await': 2,
        'no-script-url': 2,
        'no-self-compare': 2,
        'no-sequences': 2,
        'no-shadow': 2,
        'no-tabs': 2,
        'no-template-curly-in-string': 2,
        'no-throw-literal': 2,
        'no-trailing-spaces': 2,
        'no-underscore-dangle': 2,
        'no-unmodified-loop-condition': 2,
        'no-unneeded-ternary': 2,
        'no-unused-expressions': 2,
        'no-use-before-define': [2, {functions: false}], // functions are hoisted
        'no-useless-backreference': 2,
        'no-useless-call': 2,
        'no-useless-computed-key': 2,
        'no-useless-concat': 2,
        'no-useless-constructor': 2,
        'no-useless-rename': 2,
        'no-useless-return': 2,
        'no-var': 2,
        'no-whitespace-before-property': 2,
        'object-curly-newline': [2, {consistent: true}],
        'object-curly-spacing': 2,
        'object-shorthand': 2,
        'operator-assignment': 2,
        'operator-linebreak': [2, 'before'],
        'prefer-arrow-callback': 2,
        'prefer-const': 2,
        'prefer-destructuring': 2,
        'prefer-exponentiation-operator': 2,
        'prefer-numeric-literals': 2,
        'prefer-object-spread': 2,
        'prefer-promise-reject-errors': 2,
        'prefer-regex-literals': 2,
        'prefer-rest-params': 2,
        'prefer-spread': 2,
        'prefer-template': 2,
        'quote-props': [2, 'as-needed'],
        quotes: [2, 'single', {avoidEscape: true}],
        radix: 2,
        'require-atomic-updates': 2,
        'require-await': 2,
        'require-unicode-regexp': 2,
        'rest-spread-spacing': 2,
        semi: 2,
        'semi-spacing': 2,
        'semi-style': 2,
        'sort-imports': [2, {
            // match WebStorms sorting behaviour
            ignoreCase: true,
            ignoreDeclarationSort: true,
        }],
        'space-before-blocks': 2,
        'space-before-function-paren': [2, 'never'],
        'space-in-parens': 2,
        'space-infix-ops': 2,
        'space-unary-ops': 2,
        'spaced-comment': 2,
        strict: 2,
        'switch-colon-spacing': 2,
        'symbol-description': 2,
        'template-curly-spacing': 2,
        'template-tag-spacing': 2,
        'unicode-bom': 2,
        'yield-star-spacing': 2,
        yoda: 2,
    },
};
